### ISSUE TITLE
make me create a pet when i sign up or upsert pets when making a photo without pets

### ISSUE THREAD

**Issue by swyxio** [mgilangjanuar/tamagotreal#2]
great app, very functional, and nice concept! feedback: the first thing i tried to do was add a new post without having any pets added. took me a while to figure out how to add a pet then to add a post. you can combine them, and/or force me to add a pet when i sign up (or login for the first time)

**Comment by mgilangjanuar** [comment]
good idea

**Comment by mgilangjanuar** [comment]
![Screen Shot 2021-08-10 at 16 53 38](https://user-images.githubusercontent.com/3146378/128846891-c3ac0d26-1689-40c1-804e-1acb7c294aa1.png)
